### PR TITLE
Versions of walkDir and walkDirAccum with relative paths

### PR DESCRIPTION
**Pull request by mmhat**
Spares you striping prefixes all the time

### CODE REVIEW

**Comment by mrkkrp** [comment]
The idea is good, but it should be done a bit differently. I can finish up myself when I have time, or I can tell you what to do, not sure what is better.

**Comment by mmhat** [comment]
@mrkkrp Something like https://github.com/mrkkrp/path-io/pull/35?

**Comment by mrkkrp** [comment]
I could not find time to check it this weekend, but I'll get to it. It's on the top of my open-source TODO list now.

**Comment by mrkkrp** [comment]
Applied as 6dba9c076fa8b812d917c6c89eda7f0e38187255.

**Pull request closed without merging**
