### PR TITLE
Add findFileWith API from the directory package

### PR DESCRIPTION
**Pull request by harendra-kumar**

### CODE REVIEW

**Comment by mrkkrp** [comment]
A bit busy right now but I'll get to reviewing this, probably this weekend.

**Comment by mrkkrp** [comment]
This library is a wrapper around `directory` and `temporary`. Can't we just grab the function from `directory` and wrap it here? Why do we need to re-implement the stuff? I'm asking these questions because the more "custom" code we have here in `path-io`, the more responsibility I have as a maintainer that I cannot redirect to maintainers of `directory` and `temporary`.

**Comment by harendra-kumar** [comment]
I wanted to make it a wrapper but the existing `FindFilesWith` function was already re-implemented rather than wrapped so I thought that is the preferred mode for this function for whatever reason. I only upgraded the existing implementation of `FindFilesWith` to the current implementation available in the directory package. The new API `FindFileWith` that I added came free because of the common implementation.

I too prefer a wrapper instead, if you agree with that I can change both the APIs to a wrapper. I hope there is no serious reason for re-implementing the original `FindFilesWith`.

**Comment by mrkkrp** [comment]
Yes, please change them to wrappers. Also it would be good to add a test for the new function...

**Comment by mrkkrp** [comment]
Any update on this?

**Comment by mrkkrp** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
