### PR TITLE
Enable Appveyor CI to test on Windows

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by mrkkrp** [comment]
@harendra-kumar From where this `Win32` module should be imported?

* Appveyor failure: https://ci.appveyor.com/project/mrkkrp/path-io/build/1.0.1
* Relevant code: https://github.com/mrkkrp/path-io/blob/setup-appveyor-ci/Path/IO.hs#L1216

**Comment by mrkkrp** [comment]
@harendra-kumar I don't understand why `isSymlic` isn't just `isSymbolicLink` from `unix-compat`. That package is supposed to provide portable implementations, so why not use just that?

**Comment by harendra-kumar** [comment]
I was not sure if `isSymbolicLink` works correctly for windows. I did not check the implementation, `unix-compat` package doc says that not all APIs work on windows. If we can verify using the tests that`isSymbolicLink` works correctly on windows then we can get rid of the windows specific code and just use that.

**Comment by mrkkrp** [comment]
It seems that `getFileStatus` should work on both Posix and Windows. Otherwise, if adding Windows support were so easy, they would have added it already anyway. Checking this may be tricky because I only can test via Appveyor and `createSymlink` certainly does not work there (throws an exception). Maybe I could create a special test to check if `isSymbolicLink` itself is working.

**Comment by mrkkrp** [comment]
Apparently it works just fine on Windows.

**Pull request merged**
